init:
  - git config --global core.autocrlf input

build_script:
  - build.cmd

deploy:
  - provider: NuGet
    api_key:
      secure: Ie7C0UoQ6Q18B9cyczb70wRyrimai7EZZefPV7SVRbU0wTnozUd3yQ+N6NmzCPTu
    artifact: /.*\.nupkg/
    on:
      branch: master
      
nuget:
  project_feed: true
  
artifacts:
  - path: '*.nupkg'
    name: Packages